### ISSUE TITLE
Compilation error with clang++ 17

### ISSUE THREAD

**Issue by Ecordonnier** [containers/libocispec#132]
See also the original issue at https://github.com/containers/crun/issues/1446

I am trying to consume libcrun in a c++ program compiled with clang++ 17 by including libcrun/container.h in "extern C" blocks.

```
#ifdef __cplusplus
extern "C" {
#include <libcrun/container.h>
#endif

#ifdef __cplusplus
}
#endif
```

The issue is that container.h includes ocispec/runtime_spec_schema_config_schema.h, which contains the following code which uses the reserved c++ keyword "class":

```
typedef struct {
    char *class;
    int32_t priority;
    yajl_val _residual;
    unsigned int priority_present : 1;
}
```
Thus the compilation fails.

Should this be fixed by replacing the "class" keyword while generating the C header-file in https://github.com/containers/libocispec/blob/main/src/ocispec/headers.py ?

**Comment by giuseppe** [comment]
would you like to try opening a PR to fix it?

**Comment by Ecordonnier** [comment]
I can do that. I just wanted to confirm my understanding of the needed logic change first. If you agree that I modify the python scripts to replace class with class_, I'll send a PR.

**Comment by Ecordonnier** [comment]
See https://github.com/containers/libocispec/pull/133
