### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fenrig** [containers/libocispec#59]
Hi, are there any plans of moving the license from GPLv3 to GPLv2/LGPLv2.1+ like it has been done for crun: https://github.com/containers/crun/commit/34a0ff3cc9fc588bf27d959987b1ecbea6261e15. 

I believe if people want to include crun in their commercial product that the license of the libocispec is still pushing GPLv3, or am I wrong?

**Comment by giuseppe** [comment]
@fenrig the GPLv3 license covers only the libocispec code generator itself (the python scripts).

There is a bison-like exception for the generated code and it can be used under any license terms: https://github.com/containers/libocispec/pull/46

**Comment by giuseppe** [comment]
for example, [iSulad](https://gitee.com/openeuler/iSulad) that is distributed under the Mulan PSL license is using libocispec https://gitee.com/openeuler/iSula-libutils/tree/master/third_party/libocispec

**Comment by fenrig** [comment]
Thanks for the information <3
