### ISSUE TITLE
Update LICENSE to specifically layout the multi-license arrangement

### ISSUE THREAD

**Issue by vbatts** [containers/libocispec#84]
I see https://github.com/containers/libocispec/issues/59,
but if I were investigating this project the first thing I see is 
![Screenshot from 2021-03-15 07-50-05](https://user-images.githubusercontent.com/67049/111149907-d82cc000-8563-11eb-9e2e-038313aa8637.png)

If the LICENSE file isn't directly a copy from say OSI, then github won't match it as such in that space. Then folks can open the LICENSE file and see that they can still link against libocispec with bringing the copyleft license.

**Comment by giuseppe** [comment]
thanks for opening the issue.

Looking at Bison, the COPYING file is the same as used by libocispec.  I'll need to investigate this further, as I am not sure yet how we can force a different license (and https://choosealicense.com/ doesn't seem to have anything like it)

**Comment by vbatts** [comment]
then maybe even just a statement at the top of the LICENSE saying that the
license is only on the generation code, and not the output of the generated
code?

**Comment by giuseppe** [comment]
what do you think of https://github.com/containers/libocispec/pull/85 ?
